#!/bin/bash

AWS="/usr/local/bin/aws"

# get stack variables
STACK_NAME=$(git config --get aws-opsworks.stack-name)
STACK_ID=$($AWS opsworks describe-stacks --region us-east-1 | jq ".[\"Stacks\"][] | select(.Name==\"$STACK_NAME\")" | jq '.StackId' -r)
COOKBOOK_BUCKET=$(git config --get aws-opsworks.cookbook-bucket)

echo "===> Package and upload cookbooks"
berks package cookbooks.tar.gz
$AWS s3 cp cookbooks.tar.gz $COOKBOOK_BUCKET
