name 'aws-cloudwatch'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures aws-cloudwatch'
long_description 'Installs/Configures aws-cloudwatch'
version '0.1.0'
